In [1]:
import pandas as pd

df = pd.read_json('yelp_academic_dataset_review.json',lines=True)

In [2]:
df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [17]:
Positive_stars = df[(df['stars'] == 4) | (df['stars'] == 5)].sample(25000)

In [18]:
Positive_stars

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
164284,OHodTGAjtxp5lNkFOHHNDA,CMQ66mdfbGZkeU5K-KVOCw,ut6fi2W2YaipNOqvi7e0jw,5,1,0,1,Darn near perfect. Great beer ($2 pints on Sun...,2014-11-17 18:19:07
3092574,50jhqUXiH-WWoKXyidmarw,22Zd2AYOwVhMIWvS-jwebA,q-zV08jt6U-q05SMEuQJAQ,5,2,1,2,Out of all the cheesesteak places I've tried i...,2011-03-03 20:12:41
5755540,mw8yzxz0D1GXNKCSUcQUAg,I-13tlo6mFNCmpBTuUYDuw,6Gon-iz1NnzPPbwQhIG60A,5,2,0,0,I stop by during the week for their Country Br...,2014-03-24 16:32:19
451077,CJ-lc3VlU29XevfIErvZGg,um4H6Mm4xNVEr5coEGAKcg,An8CxmvuFQCe8T1uboBfXA,5,0,0,0,"Great customer service, and staff handled a ru...",2020-08-18 21:29:30
2525842,9QO-sijquoa_2veDIfFmgQ,dgf1AeYczUQbvkjbotWsQQ,akNpPdFsHk0mvbqkmPrXWg,5,0,0,0,Saki is great. Responded quickly and scheduled...,2018-05-25 17:06:40
...,...,...,...,...,...,...,...,...,...
352583,g2_nDwXQtXGVgyMTD1J9ow,IHmrY1RQzaJeQHX7ES0uLQ,LuyXtOJzCTPH5pJbslygRg,5,0,0,0,One of the best Chinese joints I've went to al...,2016-12-06 13:26:40
2232699,FkqKI1HrHdRGmdgCKNX-Bw,RnjWmBWHMc_gel3oQgrl8g,hR48gsFU8aHOjNbYm987jA,5,0,0,0,Best black and white cookies in Saint Louis. T...,2018-09-07 19:53:09
4373280,Z4TRr2WRMUQCgcCNQgx3Fg,73MRrt4TT5PUWkNwoOvhWA,UTVvCIMgSAbUx2stCRAJzQ,4,1,1,1,Their breakfast is too die for ! I love the ha...,2016-03-27 17:16:56
6404209,xXhACtWZah_qTITTEXrIDg,A_eCBvgUL8MdaR9tIo741Q,qpwCNybUXyVNepI0aiEZ7w,4,5,0,1,Hoagie City is an unassuming breakfast/lunch d...,2011-10-08 19:44:51
865537,0v7S1KgAlnIgtKE9OZLlVQ,bnPpoAsVbULVN8EsUYGGCA,Z8qGOmU8YxDjLPBbrz84Yw,4,1,1,0,After killing a whole cheesesteak sandwich for...,2016-01-19 21:11:38

In [19]:
Neutral_stars = df[(df['stars'] == 3)].sample(25000)

In [20]:
Neutral_stars

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
6006457,iUBds-pvZwgfVNROo0hxpg,YS3shR8RfHnOu5Xyi_ew4Q,6DSwG39rfdeeKz22KiRBbA,3,2,0,0,The waitresses have been around the block and ...,2017-03-13 16:41:52
935044,fDefotq_3cxVhUclG8XMpg,z67oNAZR_uHG84k3Dntckg,IORvbG2rAIVJ-1d148cCmg,3,6,8,2,"Voyeur is so sketch, but that's why you're her...",2011-09-11 17:14:58
4242865,YvnTSPvNo3Y0ojumnHTC6g,ln99M1ahEQNqKtEPFr2lTg,06BbJ-yKBlf9uHZSNGsO9Q,3,0,0,0,"They only have basic massages, no hot stones o...",2018-08-06 10:41:58
4485296,JYCGFYHCX1dRMlq197EeHQ,ao-AH4CKrHlJLdrxYm9reg,QLEPOwVEoskuTh7nmhWqMw,3,0,0,0,Not the friendliest staff but it's a generic U...,2017-10-08 13:24:46
3719021,Dh7pEqzs5YEitxIj9IZOsA,6_Bg26_Za4X2orcooY3Oxg,ZxymmM8SI80x0VxpW8h9ZQ,3,0,0,0,"Fairly standard for a Jerry Bobs, yet not one ...",2014-09-04 03:37:57
...,...,...,...,...,...,...,...,...,...
4828747,eVttt35JUSfCwbGjVjZwGw,1JIkFpJaATdeL_FSqgh0aA,gQ5_wcFqhplc9xrnSCt6-Q,3,1,0,0,Good fire oven pizza. But I had sticker shock...,2017-07-04 17:21:13
3589398,Fk_QEez5A_47XdEAJQeHRA,IFh8kiTHNguv0NiJ0TPxnw,jHZS9GIhW7s9r4w5w-0A0Q,3,0,1,0,"The server was SOOOOO sweet, which is the only...",2014-03-03 16:47:17
3653539,SZIWsNzJJN5imjlsZ7QP2A,KR2nyTod_DM_kTVgoLyGkA,oD9OWogCcsvwEP2Y_rov7Q,3,1,0,0,It's a Best Buy. All of them are pretty much e...,2011-05-04 13:08:07
1763485,vX4wNOVR2HV6cXgrMkoIaQ,_kcHxYPXRYjU4hk2xtCO0w,f9H3wpzWG_apxoumWB-Dvg,3,4,2,2,I've been coming to Equator since 2007 and I a...,2016-08-22 21:23:40
3618064,aUSDIcsZ19QD3De9wgEYCA,Ari6H4eY-GOWv_sFkpyq7Q,LdECsE8lJS7v5GTFTcjPSg,3,1,0,0,I ordered a platter and fried pickles; I wasn'...,2018-07-11 13:41:04

In [21]:
Negative_stars = df[(df['stars'] == 1) | (df['stars'] == 2)].sample(25000)

In [25]:
Negative_stars

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
1117359,eFKcDpecmwg0dk9ujc2z9w,DqdnA0rT-CrUfsMCiFfROg,LmZWlvPJBwj5WG2KHV-v1Q,1,0,1,0,Half price happy hour gets you 1/2 the normal ...,2016-02-20 06:23:06
4254142,PcVKDyBgu0iONWosoJiC5Q,7VqOMsoA72QpvGMOhR0y0A,LEyWxCngS9m5hWc9coJD4g,2,1,0,0,It sure about this place. Should be called Eve...,2016-11-15 16:57:34
632427,U6WAQi8wUYcFPqxUa82H9w,t33lxpSWtrwQID8qI9gxfw,cXAKeC-EgVChIxhS7fscmw,2,4,0,0,"Breakfast is good, but lunch not so much. I or...",2015-10-24 05:05:56
4003230,EiutUjYu8kFucSo2e9jPjg,34ijTmOavWudcZzjuCmeXQ,gujO7uy-VeqqEj9eNxSXIg,1,0,0,0,Locked the doors 15-20 mins before closing. Th...,2021-01-17 02:56:19
2442023,EItDrghfN07J8dcrqqVVlA,kjlhPieXBPx7PqX8K4aQ9A,2inupe9vXbaMd-h9TnZv5g,1,2,1,0,"Well, I really can't tell you how it is here, ...",2014-04-24 00:02:36
...,...,...,...,...,...,...,...,...,...
3906774,D-EuSAKIEUjQ9RK5fvn4Wg,yfzJiR-UbNVT6_tOd4neYA,-J0RIXNexJDV-mOAyhUJIQ,1,0,0,0,The worst rental company! Do not choose this ...,2019-04-14 02:52:49
2143534,2yg4OwdRp2gPh48eUE7r3A,Eur0z9Fa0pRucuY4WPtgEA,YgG-yAuu5sthGjl2WBa1NQ,1,0,0,0,We were visiting Florida and wanted to eat nea...,2018-02-11 22:16:26
3088030,ZkPAj2T1MKR00VgOHOJaYg,2on-VIXmdDfX0p8DR55HSg,gnpyyeWQ53WlDMJEq-YA_w,2,0,0,0,$150 bill and salty soggy food. \n\nI was here...,2011-08-17 15:33:15
2932459,myka2J-I0UO_qFGUt763bQ,DVHxau2YSLDKzg98xsl-4Q,g2zwbLIqxtN9nGGuL43trg,1,0,0,0,"A slice of pizza is pretty big, so I guess it'...",2017-05-27 19:27:52
3566017,lqIpmgABmbNoNQJ9tL_3RQ,JQ8FB6RmUnk4Ti2FiHSCJA,_MqQQaJuulw7CqiNsaG96A,2,0,0,0,"We went to see ""Unbroken"" on January 2. The la...",2015-01-21 23:54:49

In [32]:
df_List = [Positive_stars, Neutral_stars, Negative_stars]
New_df = pd.concat(df_List)

In [33]:
New_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
164284,OHodTGAjtxp5lNkFOHHNDA,CMQ66mdfbGZkeU5K-KVOCw,ut6fi2W2YaipNOqvi7e0jw,5,1,0,1,Darn near perfect. Great beer ($2 pints on Sun...,2014-11-17 18:19:07
3092574,50jhqUXiH-WWoKXyidmarw,22Zd2AYOwVhMIWvS-jwebA,q-zV08jt6U-q05SMEuQJAQ,5,2,1,2,Out of all the cheesesteak places I've tried i...,2011-03-03 20:12:41
5755540,mw8yzxz0D1GXNKCSUcQUAg,I-13tlo6mFNCmpBTuUYDuw,6Gon-iz1NnzPPbwQhIG60A,5,2,0,0,I stop by during the week for their Country Br...,2014-03-24 16:32:19
451077,CJ-lc3VlU29XevfIErvZGg,um4H6Mm4xNVEr5coEGAKcg,An8CxmvuFQCe8T1uboBfXA,5,0,0,0,"Great customer service, and staff handled a ru...",2020-08-18 21:29:30
2525842,9QO-sijquoa_2veDIfFmgQ,dgf1AeYczUQbvkjbotWsQQ,akNpPdFsHk0mvbqkmPrXWg,5,0,0,0,Saki is great. Responded quickly and scheduled...,2018-05-25 17:06:40
...,...,...,...,...,...,...,...,...,...
3906774,D-EuSAKIEUjQ9RK5fvn4Wg,yfzJiR-UbNVT6_tOd4neYA,-J0RIXNexJDV-mOAyhUJIQ,1,0,0,0,The worst rental company! Do not choose this ...,2019-04-14 02:52:49
2143534,2yg4OwdRp2gPh48eUE7r3A,Eur0z9Fa0pRucuY4WPtgEA,YgG-yAuu5sthGjl2WBa1NQ,1,0,0,0,We were visiting Florida and wanted to eat nea...,2018-02-11 22:16:26
3088030,ZkPAj2T1MKR00VgOHOJaYg,2on-VIXmdDfX0p8DR55HSg,gnpyyeWQ53WlDMJEq-YA_w,2,0,0,0,$150 bill and salty soggy food. \n\nI was here...,2011-08-17 15:33:15
2932459,myka2J-I0UO_qFGUt763bQ,DVHxau2YSLDKzg98xsl-4Q,g2zwbLIqxtN9nGGuL43trg,1,0,0,0,"A slice of pizza is pretty big, so I guess it'...",2017-05-27 19:27:52
3566017,lqIpmgABmbNoNQJ9tL_3RQ,JQ8FB6RmUnk4Ti2FiHSCJA,_MqQQaJuulw7CqiNsaG96A,2,0,0,0,"We went to see ""Unbroken"" on January 2. The la...",2015-01-21 23:54:49

In [34]:
shuffled_Df = New_df.sample(frac=1)

In [35]:
shuffled_Df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
2866685,EZhsez9rcRcnz5vzdDprgQ,Jcg0KyxNMTSlOeEfI78LMA,_9Z3cuZQBOGv_XzSG4ewHA,1,5,1,0,Went this afternoon for a birthday lunch. It w...,2015-06-10 21:51:10
4007935,UASULpgxM45JQdbuAk4o2g,6s-g2vFu12OemhiK3FJuOQ,G_VpU7J9do8ZRCLIblDBZA,3,5,1,5,"Located near Drexel and UPenn, Han-Wool (Korea...",2008-03-31 03:11:46
6726516,4NuztpkW80grQEdbRJ1HKw,NzmoFvh-YIXSJU8_k6jgdA,X7yGrz7oDbt8UY5rdmJc_w,5,1,0,0,This place has the best lunch buffet in the ci...,2019-03-23 23:16:18
1457784,LzQkTCQfO3DVXE52TKo6VA,u1LTgEJmd8FZmDxxrgHwGw,3iSRhLUZfZSlLaQw-BzloQ,5,0,0,0,This is by far my favorite spot in Nashville f...,2018-05-20 06:37:13
6891,wf-W_7E6uNJmXiSiMdvPsw,Vwslifegl59fQVOe5BH1gw,RUCsFlBuA80Wc9PmYzmayQ,3,2,0,1,This round-the-corner clothing version of the ...,2011-08-25 21:55:33
...,...,...,...,...,...,...,...,...,...
3955822,UniXnVymUjCW9mKoN_JKQA,_qpZgV3vrYUYvBD5MDW6oQ,rz325HFuVeo1qZgrnFw8YA,2,1,1,1,Staff is super friendly! I live by the area an...,2020-03-09 19:42:48
1200031,0kPJptO5U5vl5gikPrqNMw,-ftREF8vomubEfe8_CdE_w,x3RBrF6nJqhPU-8MXOA27g,1,1,0,0,Patron Alert. First time ever at Peggy O'Neill...,2019-09-30 01:48:28
4556263,RZyyNSRNoqd7SRcmM2nl5w,uXA2S9glwAFZ-boRNhkeVQ,2OXCAbz3x_MrQSYj1zarIA,1,2,1,1,"Good food, TERRIBLE service. Everyone we encou...",2017-10-29 17:51:52
4326689,DHNUXvNWGtAzMPKzutSJrw,rzRuWYc9-JOCtx2VbcxaZg,HP-GplR7ekZZpfLsupRSVA,1,2,0,0,I miss Siamese Thai so much. You can tell this...,2016-09-24 16:19:01
5643078,-8tcsPMRFHjp0tDWrJPsAg,CAKTUNTsuyCfsSpzjGptcg,lNTXXh_vrIt705lqDlDp5A,3,1,1,0,"Good bar food, best wings in St Louis. Compla...",2016-11-23 22:55:59

In [36]:
shuffled_Df.loc[shuffled_Df['stars'] == 2]

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
6022763,-eVCXAsy7CNs7ZIB7SG70A,Z9655SIfsrLQ8C466AcATw,Kg0gJ_3lGToLjuXrLY12Ng,2,0,0,0,"Well, on a positive note, rooms are large and ...",2018-08-03 16:52:59
4956041,tZAU5Ie9DLxXzLJCgfk9fw,u7T9sTYWb1Ef8kYm0qzMcQ,QK9s-Chx69_U-M2gsPb3Gw,2,0,0,0,Every single thing that was brought to our tab...,2016-02-14 16:57:54
6032674,jd094g2PRytglXygXebuzA,j-1gskpTS7P0nNWq-AtNhA,uHkO-VYglIeZafsny21O3Q,2,0,0,0,The female employee seemed bothered by our pre...,2019-02-17 14:03:57
36293,6_3NdzCFqvnMiJfc3UF1Wg,Zj_SwzaCWeiYQUD19GwbAQ,s688oKDwUayG5rjHbPwK7w,2,0,0,0,Was in the area and never been so stoped in. G...,2017-04-22 23:34:30
223015,439UPa3tzzHxXoK87DI37A,ZBCmWKnqjUNarl70phoM6g,xaiOUSSSf9rbYz_4e6dIcg,2,2,0,0,I'm have been here before and got a great gel ...,2018-03-20 20:55:24
...,...,...,...,...,...,...,...,...,...
3277206,kYSkLpJckW9LKbWPsp8a6A,3hjFgJ57yvTGSZKN363LDQ,MYZuMWSZ9-1q-_1fbWfvow,2,1,0,0,A friend and I ordered from uber eats and for ...,2020-01-02 04:27:57
4521832,ai9tYHZxr4OEck1tkJ5X2Q,IYxFMcTI-bPmAG3ptQI5TA,xotdeLae9P1mHAiJx4D0XQ,2,3,1,0,"To me, 1 star = not eatable. So I gave it 2.\n...",2013-04-24 04:45:58
663565,S2DpQbPDZ7mSObYG_c-d1w,OpKvStdqSWZqDXHdCiuZZA,D_sIoGDRaLJv0DAIc46MMA,2,0,0,0,Ayy so we like 8 people deep in this bih. And ...,2019-12-01 14:24:40
3629507,csxzEmM6ytsnRh6l-0mBeg,sLNHFRk3Bssc8VuMvehIBg,ClEUgRru8zSwV4gB32bHFQ,2,0,2,0,Way overpriced......\n\nFor the prices they ch...,2010-07-18 12:34:44
3955822,UniXnVymUjCW9mKoN_JKQA,_qpZgV3vrYUYvBD5MDW6oQ,rz325HFuVeo1qZgrnFw8YA,2,1,1,1,Staff is super friendly! I live by the area an...,2020-03-09 19:42:48

In [37]:
shuffled_Df.to_csv(path_or_buf="Shuffled_CSV.csv", index=False)